packages:
  - "apps/*"
  - "packages/*"
confirmModulesPurge: false
allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  '@scarf/scarf': false
  '@swc/core': true
  node-pty: true
  prisma: true
  sharp: true
