; Afficheur e-ink skbox — M5Stack PaperS3 (ESP32-S3R8, 16 Mo flash, 8 Mo PSRAM octal)
[env:papers3]
platform = espressif32@6.10.0
board = esp32-s3-devkitc-1
framework = arduino
board_build.arduino.memory_type = qio_opi
board_build.flash_mode = qio
board_build.psram_type = opi
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_build.partitions = default_16MB.csv
build_flags =
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
lib_deps =
    m5stack/M5Unified@^0.2.23
    m5stack/M5GFX@^0.2.30
    bblanchon/ArduinoJson@^7.2.0
monitor_speed = 115200
